### ISSUE TITLE
Divide Team into Two Sub-teams

### ISSUE THREAD

**Issue by moeezumer6754** [moeezumer6754/Group02-Discrete#3]
Objective:
We are dividing our team into two groups to streamline the development process:

Team 1 (Frontend): Will focus on the user interface, including UI/UX design and implementing visual components.
Team 2 (Logic): Will focus on the core application logic, including backend processing, data handling, and functionality.
Role Breakdown:

Team 1 - Frontend:
Responsible for designing and implementing the user interface.
Ensures the system is visually appealing and easy to use.

Team 2 - Logic:
Develops the application's core functionality.
Handles server-side processes, algorithms, and integration with the frontend.

Coordination:
To ensure effective collaboration, one team member will act as a linker to manage communication and integration between the two teams.

Discussion Points:
Who wants to join Team 1 (Frontend)?
Who wants to join Team 2 (Logic)?
Who is interested in being the linker?

Suggested Split:
2 members in Frontend (Team 1).
2 members in Logic (Team 2).
1 member as the linker.

Next Steps:
Please share your team preference (Frontend or Logic).
Mention if you’re interested in taking the linker role.
Let us know if you have any concerns or suggestions.

Deadline:
Respond by 15-11-24 to finalize the teams and start working effectively.

**Comment by Fasih160** [comment]
Hi Team,

I'd like to join Team 2 (Logic) for our password strength checking app. I’m passionate about backend development and have experience in server-side processes and algorithms. I believe my skills and attention to detail will help us build a robust and efficient application.

Thanks for considering!

**Comment by luqman23054** [comment]
Hi Team,

I’d like to join Team 1 which will be the frontend team for our password strength checking app. I have experience in Android Studio, HTML, CSS, and Java/Kotlin. I believe my skills in creating intuitive user interfaces and attention to detail will help us build a seamless and engaging user experience.

Thanks for considering my request!

**Comment by shamoonasadk** [comment]
**Salam Team,** 

I want to join the Backend (Logic) team because I enjoy working on applications' core functionality. I’m interested in handling data, building efficient systems, and making sure everything runs smoothly behind the scenes. Backend development is challenging but rewarding, and I like creating solutions that connect well with the front end. 
I’m excited to contribute to building a strong and reliable foundation for the project.

Thanks for your kind consideration!
